# Generated by Django 2.2.6 on 2023-03-31 11:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proprietor_name', models.CharField(max_length=40)),
                ('Mobile_Number', models.CharField(max_length=40)),
                ('Email_ID', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=40)),
                ('verified', models.BooleanField(default=False)),
                ('assigned_distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dependency', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=40)),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('colour', models.CharField(max_length=40)),
                ('chassis_number', models.CharField(max_length=40)),
                ('verified', models.BooleanField(default=False)),
                ('vehicle_transfer_number', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papad_type', models.CharField(choices=[('Udid_Papad', 'Udid Papad'), ('Garlic_Papad', 'Garlic Papad'), ('Rice_Papad', 'Rice Papad'), ('Ragi_Papad', 'Ragi Papad'), ('Aloo_Papad', 'Aloo Papad'), ('Sabudana_Papad', 'Sabudana Papad')], max_length=40)),
                ('quantity', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comment', models.CharField(max_length=40)),
                ('acknowledgement', models.BooleanField(default=False)),
                ('order_placed', models.BooleanField(default=False)),
                ('responsible_firm_of_this_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_responsible_firm', to='todo.User_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name_order_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
