# Generated by Django 2.2.6 on 2023-04-01 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_info',
            name='user',
        ),
        migrations.AlterField(
            model_name='order_info',
            name='responsible_firm_of_this_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_responsible_firm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='Vehicle_info',
        ),
    ]
