# Generated by Django 2.2.6 on 2023-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20230401_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_inventry_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_qty', models.PositiveIntegerField()),
                ('ideal_qty', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=40)),
            ],
        ),
    ]
