# Generated by Django 2.2.6 on 2023-04-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_product_inventry_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_inventry_info',
            name='comment',
            field=models.CharField(default='comment', max_length=40),
        ),
    ]
