# Generated by Django 2.2.6 on 2023-04-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20230418_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='raw_inventry_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_qty', models.PositiveIntegerField()),
                ('ideal_qty', models.PositiveIntegerField()),
                ('comment', models.CharField(default='comment', max_length=40)),
            ],
        ),
    ]
